import { Component, OnInit } from '@angular/core';
import { DashboardServiceService } from '../dashboard-service.service';

@Component({
  selector: 'app-quotes',
  templateUrl: './quotes.component.html',
  styleUrls: ['./quotes.component.scss']
})
export class QuotesComponent implements OnInit {

  constructor(
    private dashboardService: DashboardServiceService
  ) { }

  color;
  logo;
  quoteDetails;
  first = 0;
  rows = 10;

  cols = [
    { field: 'quoteId', header: 'Quote Id' },
    { field: 'quoteName', header: 'Quote Name' },
    { field: 'description', header: 'Description' },
    { field: 'statusDesc', header: 'Status' },
    { field: 'issueDate', header: 'Quote Issue Date' },
    { field: 'validFromDate', header: 'Valid From Date' },
    { field: 'validThruDate', header: 'Valid Thru Date' }
  ];

  ngOnInit(): void {
    this.color = localStorage.getItem("fontColor");
    this.logo = localStorage.getItem("logo");
    this.getQuotes();
  }

  next() {
    this.first = this.first + this.rows;
  }

  prev() {
    this.first = this.first - this.rows;
  }

  reset() {
    this.first = 0;
  }

  isLastPage(): boolean {
    return this.first === (this.quoteDetails.length - this.rows);
  }

  isFirstPage(): boolean {
    return this.first === 0;
  }

  getQuotes(): void {

    this.quoteDetails = [
        {
          "quoteId": "10212",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "10021",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": "1585652717000",
          "validThruDate": null,
          "quoteName": null,
          "description": null,
          "lastUpdatedStamp": 1585652765648,
          "lastUpdatedTxStamp": 1585652765642,
          "createdStamp": 1585652734950,
          "createdTxStamp": 1585652734935,
          "contactPartyId": "17171",
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10020",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "10010",
          "issueDate": null,
          "statusId": "QUO_SENT",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": 1586936100000,
          "validThruDate": 1587022500000,
          "quoteName": "CHITA",
          "description": null,
          "lastUpdatedStamp": 1586936152976,
          "lastUpdatedTxStamp": 1586936152937,
          "createdStamp": 1578046822155,
          "createdTxStamp": 1578046822138,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Sent"
        },
        {
          "quoteId": "10213",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17172",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "asd",
          "description": null,
          "lastUpdatedStamp": 1585656918064,
          "lastUpdatedTxStamp": 1585656918037,
          "createdStamp": 1585656889481,
          "createdTxStamp": 1585656889448,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10214",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17173",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "test999",
          "description": "Accessory",
          "lastUpdatedStamp": 1585660003126,
          "lastUpdatedTxStamp": 1585660003122,
          "createdStamp": 1585659754715,
          "createdTxStamp": 1585659754697,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10215",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17174",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "staging test",
          "description": null,
          "lastUpdatedStamp": 1585719357632,
          "lastUpdatedTxStamp": 1585719357629,
          "createdStamp": 1585719262692,
          "createdTxStamp": 1585719262672,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10216",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17175",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "quotes00",
          "description": null,
          "lastUpdatedStamp": 1585722589684,
          "lastUpdatedTxStamp": 1585722589681,
          "createdStamp": 1585722522808,
          "createdTxStamp": 1585722522781,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10070",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "16982",
          "issueDate": null,
          "statusId": "QUO_FINALIZED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "AMAZON_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "Large discount",
          "description": "Join the Employee table",
          "lastUpdatedStamp": 1582631954963,
          "lastUpdatedTxStamp": 1582631954961,
          "createdStamp": 1582107969716,
          "createdTxStamp": 1582107969452,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Finalized"
        },
        {
          "quoteId": "10220",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "5010000",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "Sahil Test",
          "description": null,
          "lastUpdatedStamp": 1586166960952,
          "lastUpdatedTxStamp": 1586166960942,
          "createdStamp": 1586166907460,
          "createdTxStamp": 1586166907426,
          "contactPartyId": "15873",
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10091",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "Company",
          "issueDate": null,
          "statusId": "QUO_SENT",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "Test",
          "description": null,
          "lastUpdatedStamp": 1582809761639,
          "lastUpdatedTxStamp": 1582809761636,
          "createdStamp": 1582809734661,
          "createdTxStamp": 1582809734647,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Sent"
        },
        {
          "quoteId": "10093",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "1230000",
          "issueDate": null,
          "statusId": "QUO_SENT",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "Testing",
          "description": null,
          "lastUpdatedStamp": 1582892894235,
          "lastUpdatedTxStamp": 1582892894233,
          "createdStamp": 1582878180379,
          "createdTxStamp": 1582878180364,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Sent"
        },
        {
          "quoteId": "10241",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17175",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": null,
          "description": null,
          "lastUpdatedStamp": 1586786365295,
          "lastUpdatedTxStamp": 1586786365287,
          "createdStamp": 1586786305985,
          "createdTxStamp": 1586786305963,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10100",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "16982",
          "issueDate": null,
          "statusId": "QUO_SENT",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": null,
          "description": null,
          "lastUpdatedStamp": 1583132985825,
          "lastUpdatedTxStamp": 1583132985822,
          "createdStamp": 1583131830131,
          "createdTxStamp": 1583131830115,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Sent"
        },
        {
          "quoteId": "10110",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17031",
          "issueDate": null,
          "statusId": "QUO_SENT",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "staging",
          "description": null,
          "lastUpdatedStamp": 1583137143026,
          "lastUpdatedTxStamp": 1583137143024,
          "createdStamp": 1583137025750,
          "createdTxStamp": 1583137025715,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Sent"
        },
        {
          "quoteId": "10111",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17032",
          "issueDate": null,
          "statusId": "QUO_SENT",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "WEB_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "skulocity Quotes test",
          "description": "17032",
          "lastUpdatedStamp": 1583137781690,
          "lastUpdatedTxStamp": 1583137781687,
          "createdStamp": 1583137720802,
          "createdTxStamp": 1583137720784,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Sent"
        },
        {
          "quoteId": "10121",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "4950000",
          "issueDate": null,
          "statusId": "QUO_SENT",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "test",
          "description": null,
          "lastUpdatedStamp": 1583302645889,
          "lastUpdatedTxStamp": 1583302645886,
          "createdStamp": 1583302608442,
          "createdTxStamp": 1583302608428,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Sent"
        },
        {
          "quoteId": "10122",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "1230000",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "test",
          "description": null,
          "lastUpdatedStamp": 1583306679690,
          "lastUpdatedTxStamp": 1583306679687,
          "createdStamp": 1583306628347,
          "createdTxStamp": 1583306628330,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10123",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "7234",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "test2",
          "description": "test2",
          "lastUpdatedStamp": 1583314081779,
          "lastUpdatedTxStamp": 1583314081776,
          "createdStamp": 1583313685676,
          "createdTxStamp": 1583313685662,
          "contactPartyId": "12770",
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10131",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "7323",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "test 6",
          "description": null,
          "lastUpdatedStamp": 1583405510857,
          "lastUpdatedTxStamp": 1583405510849,
          "createdStamp": 1583405486868,
          "createdTxStamp": 1583405486847,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10140",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17067",
          "issueDate": null,
          "statusId": "QUO_FINALIZED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "Suraj QA",
          "description": "170671706717067",
          "lastUpdatedStamp": 1583492030829,
          "lastUpdatedTxStamp": 1583492030826,
          "createdStamp": 1583491672128,
          "createdTxStamp": 1583491672099,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Finalized"
        },
        {
          "quoteId": "10141",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "6230000",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "test 7",
          "description": null,
          "lastUpdatedStamp": 1583905636579,
          "lastUpdatedTxStamp": 1583905636576,
          "createdStamp": 1583905627578,
          "createdTxStamp": 1583905627558,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10130",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17061",
          "issueDate": null,
          "statusId": "QUO_CANCELLED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": null,
          "description": null,
          "lastUpdatedStamp": 1583929856224,
          "lastUpdatedTxStamp": 1583929856221,
          "createdStamp": 1583392498190,
          "createdTxStamp": 1583392498171,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Cancelled"
        },
        {
          "quoteId": "10040",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "10022",
          "issueDate": null,
          "statusId": "QUO_FINALIZED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "Testing",
          "description": null,
          "lastUpdatedStamp": 1583930856481,
          "lastUpdatedTxStamp": 1583930856478,
          "createdStamp": 1580380102193,
          "createdTxStamp": 1580380102129,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Finalized"
        },
        {
          "quoteId": "10030",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "7320000",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "24 into 7",
          "description": null,
          "lastUpdatedStamp": 1583930958536,
          "lastUpdatedTxStamp": 1583930958533,
          "createdStamp": 1578053208322,
          "createdTxStamp": 1578053208301,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10150",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "5080000",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "test 9",
          "description": null,
          "lastUpdatedStamp": 1584001693537,
          "lastUpdatedTxStamp": 1584001693532,
          "createdStamp": 1584000636948,
          "createdTxStamp": 1584000636930,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10170",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "5490000",
          "issueDate": null,
          "statusId": "QUO_SENT",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "Mail Test",
          "description": null,
          "lastUpdatedStamp": 1584086609047,
          "lastUpdatedTxStamp": 1584086609040,
          "createdStamp": 1584084129239,
          "createdTxStamp": 1584084129198,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Sent"
        },
        {
          "quoteId": "10160",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "7090000",
          "issueDate": null,
          "statusId": "QUO_SENT",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "test13",
          "description": null,
          "lastUpdatedStamp": 1584098192364,
          "lastUpdatedTxStamp": 1584098192357,
          "createdStamp": 1584083071246,
          "createdTxStamp": 1584083071229,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Sent"
        },
        {
          "quoteId": "10180",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "DemoLBAcct",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "10111",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": null,
          "description": null,
          "lastUpdatedStamp": 1584101771158,
          "lastUpdatedTxStamp": 1584101771154,
          "createdStamp": 1584101699967,
          "createdTxStamp": 1584101699945,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10064",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "16961",
          "issueDate": null,
          "statusId": "QUO_FINALIZED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "Discount",
          "description": null,
          "lastUpdatedStamp": 1584102235718,
          "lastUpdatedTxStamp": 1584102235715,
          "createdStamp": 1581675384908,
          "createdTxStamp": 1581675384895,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Finalized"
        },
        {
          "quoteId": "10260",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17240",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "prince",
          "description": null,
          "lastUpdatedStamp": 1587725071233,
          "lastUpdatedTxStamp": 1587725071220,
          "createdStamp": 1587724863479,
          "createdTxStamp": 1587724863439,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10210",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17170",
          "issueDate": null,
          "statusId": "QUO_SENT",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "AB",
          "description": null,
          "lastUpdatedStamp": 1585638873376,
          "lastUpdatedTxStamp": 1585638873362,
          "createdStamp": 1585637611933,
          "createdTxStamp": 1585637611912,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Sent"
        },
        {
          "quoteId": "10270",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "17250",
          "issueDate": null,
          "statusId": "QUO_APPROVED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": "raj test2",
          "description": null,
          "lastUpdatedStamp": 1588157074587,
          "lastUpdatedTxStamp": 1588157074582,
          "createdStamp": 1588157037681,
          "createdTxStamp": 1588157037654,
          "contactPartyId": null,
          "createdByPartyId": "admin",
          "statusDesc": "Approved"
        },
        {
          "quoteId": "10060",
          "quoteTypeId": "PRODUCT_QUOTE",
          "partyId": "1230000",
          "issueDate": null,
          "statusId": "QUO_FINALIZED",
          "currencyUomId": "USD",
          "productStoreId": "9000",
          "salesChannelEnumId": "GC_SALES_CHANNEL",
          "validFromDate": null,
          "validThruDate": null,
          "quoteName": null,
          "description": null,
          "lastUpdatedStamp": 1585653342598,
          "lastUpdatedTxStamp": 1585653342594,
          "createdStamp": 1581662223050,
          "createdTxStamp": 1581662223017,
          "contactPartyId": "5180000",
          "createdByPartyId": "admin",
          "statusDesc": "Finalized"
        }
      ];


    this.dashboardService.findQuotes().subscribe((res) => {
      console.log(res);
    })
  }

}
