import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { DashboardServiceService } from '../dashboard-service.service';

@Component({
  selector: 'app-view-quotes',
  templateUrl: './view-quotes.component.html',
  styleUrls: ['./view-quotes.component.scss']
})
export class ViewQuotesComponent implements OnInit {

  constructor(
    private route: ActivatedRoute,
    private dashboardService: DashboardServiceService
  ) { }

  urlSubscriber: any;
  first = 0;
  rows = 10;
  resp;

  cols = [
    { field: 'quantity', header: 'Quantity' },
    { field: 'description', header: 'Description' },
    { field: 's3SmallImageUrl', header: 'Image' },
    { field: 'quoteUnitPrice', header: 'Quote Unit Price' },
    { field: 'extended', header: 'Extended' },
    { field: 'comments', header: 'Comments' }
  ];

  ngOnInit(): void {

    this.resp = {
      "quoteItemList": [
        {
          "quoteId": "10020",
          "quoteItemSeqId": "00002",
          "productId": "GZ-5708",
          "productFeatureId": null,
          "deliverableTypeId": null,
          "skillTypeId": null,
          "uomId": null,
          "workEffortId": null,
          "custRequestId": null,
          "custRequestItemSeqId": null,
          "quantity": 4.000000,
          "selectedAmount": null,
          "quoteUnitPrice": 302.00,
          "reservStart": null,
          "reservLength": null,
          "reservPersons": null,
          "configId": null,
          "estimatedDeliveryDate": null,
          "comments": null,
          "isPromo": null,
          "lastUpdatedStamp": 1581662913937,
          "lastUpdatedTxStamp": 1581662913921,
          "createdStamp": 1581662913933,
          "createdTxStamp": 1581662913921,
          "description": "Butter milk",
          "quoteApproval": {
            "productId": "GZ-5708",
            "quoteItemSeqId": "00002",
            "quoteId": "10020",
            "isApproved": "Y",
            "comments": "",
            "lastUpdatedStamp": 1584364389909,
            "lastUpdatedTxStamp": 1584364389909,
            "createdStamp": 1584364389909,
            "createdTxStamp": 1584364389909
          },
          "totalQuoteItemAdjustmentAmount": 0.0,
          "totalQuoteItemAmount": 1208.0,
          "productContent": {
            "imageServerPath": "/home/ubuntu/skulocity-opentaps/skulocity-opentaps/framework/images/webapp/images",
            "imageNameLarge": "/images/products/large/GZ-5708",
            "tryEntity": true,
            "imageNameMedium": "/images/products/medium/GZ-5708",
            "imageNameOriginal": "/images/products/original/GZ-5708",
            "productContent": [
  
            ],
            "imageFilenameFormat": "${location}/${type}/${id}",
            "imageUrlPrefix": "/images",
            "imageNameSmall": "/images/products/small/GZ-5708",
            "imageNameDetail": "/images/products/detail/GZ-5708",
            "responseMessage": "success",
            "imageMap": {
  
            },
            "product": {
              "productId": "GZ-5708",
              "productTypeId": "FINISHED_GOOD",
              "primaryProductCategoryId": null,
              "manufacturerPartyId": null,
              "facilityId": null,
              "introductionDate": null,
              "releaseDate": null,
              "supportDiscontinuationDate": null,
              "salesDiscontinuationDate": null,
              "salesDiscWhenNotAvail": null,
              "internalName": "Butter milk",
              "brandName": null,
              "comments": null,
              "productName": "Butter milk",
              "description": null,
              "longDescription": null,
              "priceDetailText": null,
              "smallImageUrl": null,
              "mediumImageUrl": null,
              "largeImageUrl": null,
              "detailImageUrl": null,
              "originalImageUrl": null,
              "detailScreen": null,
              "inventoryMessage": null,
              "requireInventory": null,
              "quantityUomId": null,
              "quantityIncluded": null,
              "piecesIncluded": null,
              "requireAmount": null,
              "fixedAmount": null,
              "amountUomTypeId": null,
              "weightUomId": null,
              "weight": null,
              "productWeight": null,
              "heightUomId": null,
              "productHeight": null,
              "shippingHeight": null,
              "widthUomId": null,
              "productWidth": null,
              "shippingWidth": null,
              "depthUomId": null,
              "productDepth": null,
              "shippingDepth": null,
              "diameterUomId": null,
              "productDiameter": null,
              "productRating": null,
              "ratingTypeEnum": null,
              "returnable": null,
              "taxable": null,
              "chargeShipping": null,
              "autoCreateKeywords": null,
              "includeInPromotions": null,
              "isVirtual": "N",
              "isVariant": "N",
              "virtualVariantMethodEnum": null,
              "originGeoId": null,
              "requirementMethodEnumId": null,
              "billOfMaterialLevel": 0,
              "reservMaxPersons": null,
              "reserv2ndPPPerc": null,
              "reservNthPPPerc": null,
              "configId": null,
              "createdDate": 1579590927686,
              "createdByUserLogin": "admin",
              "lastModifiedDate": 1579590927686,
              "lastModifiedByUserLogin": "admin",
              "inShippingBox": "N",
              "defaultShipmentBoxTypeId": null,
              "lastUpdatedStamp": 1579590927686,
              "lastUpdatedTxStamp": 1579590927684,
              "createdStamp": 1579590927686,
              "createdTxStamp": 1579590927684,
              "isActive": null,
              "publishedScopeId": null,
              "shopifyFulfillmentService": null
            }
          }
        },
        {
          "quoteId": "10020",
          "quoteItemSeqId": "00003",
          "productId": "GZ-4994",
          "productFeatureId": null,
          "deliverableTypeId": null,
          "skillTypeId": null,
          "uomId": null,
          "workEffortId": null,
          "custRequestId": null,
          "custRequestItemSeqId": null,
          "quantity": 3.000000,
          "selectedAmount": null,
          "quoteUnitPrice": 1016.00,
          "reservStart": null,
          "reservLength": null,
          "reservPersons": null,
          "configId": null,
          "estimatedDeliveryDate": null,
          "comments": null,
          "isPromo": null,
          "lastUpdatedStamp": 1581662913946,
          "lastUpdatedTxStamp": 1581662913940,
          "createdStamp": 1581662913942,
          "createdTxStamp": 1581662913940,
          "description": "Butter milk",
          "quoteApproval": {
            "productId": "GZ-4994",
            "quoteItemSeqId": "00003",
            "quoteId": "10020",
            "isApproved": "N",
            "comments": "",
            "lastUpdatedStamp": 1585652397949,
            "lastUpdatedTxStamp": 1585652397949,
            "createdStamp": 1585652397949,
            "createdTxStamp": 1585652397949
          },
          "totalQuoteItemAdjustmentAmount": 0.0,
          "totalQuoteItemAmount": 3048.0,
          "productContent": {
            "imageServerPath": "/home/ubuntu/skulocity-opentaps/skulocity-opentaps/framework/images/webapp/images",
            "imageNameLarge": "/images/products/large/GZ-4994",
            "tryEntity": true,
            "imageNameMedium": "/images/products/medium/GZ-4994",
            "imageNameOriginal": "/images/products/original/GZ-4994",
            "productContent": [
  
            ],
            "imageFilenameFormat": "${location}/${type}/${id}",
            "imageUrlPrefix": "/images",
            "imageNameSmall": "/images/products/small/GZ-4994",
            "imageNameDetail": "/images/products/detail/GZ-4994",
            "responseMessage": "success",
            "imageMap": {
  
            },
            "product": {
              "productId": "GZ-4994",
              "productTypeId": "FINISHED_GOOD",
              "primaryProductCategoryId": null,
              "manufacturerPartyId": null,
              "facilityId": null,
              "introductionDate": null,
              "releaseDate": null,
              "supportDiscontinuationDate": null,
              "salesDiscontinuationDate": null,
              "salesDiscWhenNotAvail": null,
              "internalName": "Butter milk",
              "brandName": null,
              "comments": null,
              "productName": "Butter milk",
              "description": null,
              "longDescription": null,
              "priceDetailText": null,
              "smallImageUrl": null,
              "mediumImageUrl": null,
              "largeImageUrl": null,
              "detailImageUrl": null,
              "originalImageUrl": null,
              "detailScreen": null,
              "inventoryMessage": null,
              "requireInventory": null,
              "quantityUomId": null,
              "quantityIncluded": null,
              "piecesIncluded": null,
              "requireAmount": null,
              "fixedAmount": null,
              "amountUomTypeId": null,
              "weightUomId": null,
              "weight": null,
              "productWeight": null,
              "heightUomId": null,
              "productHeight": null,
              "shippingHeight": null,
              "widthUomId": null,
              "productWidth": null,
              "shippingWidth": null,
              "depthUomId": null,
              "productDepth": null,
              "shippingDepth": null,
              "diameterUomId": null,
              "productDiameter": null,
              "productRating": null,
              "ratingTypeEnum": null,
              "returnable": null,
              "taxable": null,
              "chargeShipping": null,
              "autoCreateKeywords": null,
              "includeInPromotions": null,
              "isVirtual": "N",
              "isVariant": "N",
              "virtualVariantMethodEnum": null,
              "originGeoId": null,
              "requirementMethodEnumId": null,
              "billOfMaterialLevel": 0,
              "reservMaxPersons": null,
              "reserv2ndPPPerc": null,
              "reservNthPPPerc": null,
              "configId": null,
              "createdDate": 1579591793850,
              "createdByUserLogin": "admin",
              "lastModifiedDate": 1579591793850,
              "lastModifiedByUserLogin": "admin",
              "inShippingBox": "N",
              "defaultShipmentBoxTypeId": null,
              "lastUpdatedStamp": 1579591793850,
              "lastUpdatedTxStamp": 1579591793848,
              "createdStamp": 1579591793850,
              "createdTxStamp": 1579591793848,
              "isActive": null,
              "publishedScopeId": null,
              "shopifyFulfillmentService": null
            }
          }
        },
        {
          "quoteId": "10020",
          "quoteItemSeqId": "00004",
          "productId": "GZ-4974",
          "productFeatureId": null,
          "deliverableTypeId": null,
          "skillTypeId": null,
          "uomId": null,
          "workEffortId": null,
          "custRequestId": null,
          "custRequestItemSeqId": null,
          "quantity": 2.000000,
          "selectedAmount": null,
          "quoteUnitPrice": 1036.00,
          "reservStart": null,
          "reservLength": null,
          "reservPersons": null,
          "configId": null,
          "estimatedDeliveryDate": null,
          "comments": null,
          "isPromo": null,
          "lastUpdatedStamp": 1581662913955,
          "lastUpdatedTxStamp": 1581662913947,
          "createdStamp": 1581662913951,
          "createdTxStamp": 1581662913947,
          "description": "Butter milk",
          "quoteApproval": {
            "productId": "GZ-4974",
            "quoteItemSeqId": "00004",
            "quoteId": "10020",
            "isApproved": "N",
            "comments": "",
            "lastUpdatedStamp": 1585652397955,
            "lastUpdatedTxStamp": 1585652397955,
            "createdStamp": 1585652397955,
            "createdTxStamp": 1585652397955
          },
          "totalQuoteItemAdjustmentAmount": 0.0,
          "totalQuoteItemAmount": 2072.0,
          "productContent": {
            "imageServerPath": "/home/ubuntu/skulocity-opentaps/skulocity-opentaps/framework/images/webapp/images",
            "imageNameLarge": "/images/products/large/GZ-4974",
            "tryEntity": true,
            "imageNameMedium": "/images/products/medium/GZ-4974",
            "imageNameOriginal": "/images/products/original/GZ-4974",
            "productContent": [
  
            ],
            "imageFilenameFormat": "${location}/${type}/${id}",
            "imageUrlPrefix": "/images",
            "imageNameSmall": "/images/products/small/GZ-4974",
            "imageNameDetail": "/images/products/detail/GZ-4974",
            "responseMessage": "success",
            "imageMap": {
  
            },
            "product": {
              "productId": "GZ-4974",
              "productTypeId": "FINISHED_GOOD",
              "primaryProductCategoryId": null,
              "manufacturerPartyId": null,
              "facilityId": null,
              "introductionDate": null,
              "releaseDate": null,
              "supportDiscontinuationDate": null,
              "salesDiscontinuationDate": null,
              "salesDiscWhenNotAvail": null,
              "internalName": "Butter milk",
              "brandName": null,
              "comments": null,
              "productName": "Butter milk",
              "description": null,
              "longDescription": null,
              "priceDetailText": null,
              "smallImageUrl": null,
              "mediumImageUrl": null,
              "largeImageUrl": null,
              "detailImageUrl": null,
              "originalImageUrl": null,
              "detailScreen": null,
              "inventoryMessage": null,
              "requireInventory": null,
              "quantityUomId": null,
              "quantityIncluded": null,
              "piecesIncluded": null,
              "requireAmount": null,
              "fixedAmount": null,
              "amountUomTypeId": null,
              "weightUomId": null,
              "weight": null,
              "productWeight": null,
              "heightUomId": null,
              "productHeight": null,
              "shippingHeight": null,
              "widthUomId": null,
              "productWidth": null,
              "shippingWidth": null,
              "depthUomId": null,
              "productDepth": null,
              "shippingDepth": null,
              "diameterUomId": null,
              "productDiameter": null,
              "productRating": null,
              "ratingTypeEnum": null,
              "returnable": null,
              "taxable": null,
              "chargeShipping": null,
              "autoCreateKeywords": null,
              "includeInPromotions": null,
              "isVirtual": "N",
              "isVariant": "N",
              "virtualVariantMethodEnum": null,
              "originGeoId": null,
              "requirementMethodEnumId": null,
              "billOfMaterialLevel": 0,
              "reservMaxPersons": null,
              "reserv2ndPPPerc": null,
              "reservNthPPPerc": null,
              "configId": null,
              "createdDate": 1579591795946,
              "createdByUserLogin": "admin",
              "lastModifiedDate": 1579591795946,
              "lastModifiedByUserLogin": "admin",
              "inShippingBox": "N",
              "defaultShipmentBoxTypeId": null,
              "lastUpdatedStamp": 1579591795946,
              "lastUpdatedTxStamp": 1579591795945,
              "createdStamp": 1579591795946,
              "createdTxStamp": 1579591795945,
              "isActive": null,
              "publishedScopeId": null,
              "shopifyFulfillmentService": null
            }
          }
        },
        {
          "quoteId": "10020",
          "quoteItemSeqId": "00006",
          "productId": "GZ-1000",
          "productFeatureId": null,
          "deliverableTypeId": null,
          "skillTypeId": null,
          "uomId": null,
          "workEffortId": null,
          "custRequestId": null,
          "custRequestItemSeqId": null,
          "quantity": 1.000000,
          "selectedAmount": null,
          "quoteUnitPrice": 1111.00,
          "reservStart": null,
          "reservLength": null,
          "reservPersons": null,
          "configId": null,
          "estimatedDeliveryDate": null,
          "comments": null,
          "isPromo": null,
          "lastUpdatedStamp": 1584355886285,
          "lastUpdatedTxStamp": 1584355886276,
          "createdStamp": 1584355886281,
          "createdTxStamp": 1584355886276,
          "description": "Tiny Gizmo",
          "quoteApproval": {
            "productId": "GZ-1000",
            "quoteItemSeqId": "00006",
            "quoteId": "10020",
            "isApproved": "Y",
            "comments": "4324",
            "lastUpdatedStamp": 1584364999997,
            "lastUpdatedTxStamp": 1584364999997,
            "createdStamp": 1584364999997,
            "createdTxStamp": 1584364999997
          },
          "totalQuoteItemAdjustmentAmount": 0.0,
          "totalQuoteItemAmount": 1111.0,
          "productContent": {
            "imageServerPath": "/home/ubuntu/skulocity-opentaps/skulocity-opentaps/framework/images/webapp/images",
            "imageNameLarge": "/images/products/large/GZ-1000",
            "tryEntity": true,
            "imageNameMedium": "/images/products/medium/GZ-1000",
            "imageNameOriginal": "/images/products/original/GZ-1000",
            "productContent": [
              {
                "productId": "GZ-1000",
                "contentId": "10140",
                "productContentTypeId": "SPECIFICATION",
                "fromDate": 1586822400000,
                "thruDate": 1586908800000,
                "purchaseFromDate": 1586822400000,
                "purchaseThruDate": 1586995200000,
                "useCountLimit": null,
                "useTime": null,
                "useTimeUomId": null,
                "useRoleTypeId": null,
                "lastUpdatedStamp": 1586866694972,
                "lastUpdatedTxStamp": 1586866694722,
                "createdStamp": 1586866694972,
                "createdTxStamp": 1586866694722
              },
              {
                "productId": "GZ-1000",
                "contentId": "10128",
                "productContentTypeId": "SPECIFICATION",
                "fromDate": 1586908800000,
                "thruDate": 1586995200000,
                "purchaseFromDate": 1587600000000,
                "purchaseThruDate": 1587340800000,
                "useCountLimit": null,
                "useTime": null,
                "useTimeUomId": null,
                "useRoleTypeId": null,
                "lastUpdatedStamp": 1587018837065,
                "lastUpdatedTxStamp": 1587018837015,
                "createdStamp": 1586845753886,
                "createdTxStamp": 1586845753871
              },
              {
                "productId": "GZ-1000",
                "contentId": "10130",
                "productContentTypeId": "SPECIFICATION",
                "fromDate": 1579178746552,
                "thruDate": 1579178746552,
                "purchaseFromDate": null,
                "purchaseThruDate": null,
                "useCountLimit": null,
                "useTime": null,
                "useTimeUomId": null,
                "useRoleTypeId": null,
                "lastUpdatedStamp": 1587019246307,
                "lastUpdatedTxStamp": 1587019246259,
                "createdStamp": 1586858766063,
                "createdTxStamp": 1586858764584
              }
            ],
            "imageFilenameFormat": "${location}/${type}/${id}",
            "imageUrlPrefix": "/images",
            "imageNameSmall": "/images/products/small/GZ-1000",
            "imageNameDetail": "/images/products/detail/GZ-1000",
            "responseMessage": "success",
            "imageMap": {
              "s3SmallImageUrl": "https://s3.amazonaws.com/skulocity-development/product-images/GZ-1000_small.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMSJHMEUCIQDkzj1TRHl0yI9N3gX5%2BVadDvPYTD8QgLRyJNuN2%2FqQ3gIgBLrDHS2lAS5JcbL8Gf4PSfDa9MKysrClt8xT2IhG4ngqvQMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNzA2MzQ0MTQxNTQiDK8vg0sITnwokphOACqRA5d2mEmS9j5F%2BgX5vxyuFMdYJxTTG7fnoXmNOIShmXhG7NcsViG5Cdv%2B7ZsVN%2FOTrjaHB7%2B3YgYDKDLmmFuoIXa8sCZD9QY%2BltODB3qqc74A2E5YTPnl3M6Il%2F7F8Qxfnnm34ybNINADdsiwr9JELRO4sus9CIpn3w9Gg5U7zvhNBVGM%2BHjUbpSSFIYNU3op6ZuH%2BymISZNwi5YUXWANnOGQQ%2FKHoko8pW3cNWt%2FT9mkYmTtFcCAHCMpYd8xXEdfqOT3IdomQGayKQN8Vgo3nwxN5w6hV56YJC%2BboMg5GP%2Bial%2Bx3RASWt2yCmqQBDhP6kkQ2Kz4YjOgVA2ki3KrAS2tTb%2BQESe6UF6rojnnNFdWb9faQbLORDFdUAYGYiYrtmIwdA2%2FByzKoqmn%2BwO7d3IDsfH4RGbuleuCc5tTNqonJKTWTrwS%2BnSKv2NONjvS1gNUEVdCu7k9KnrRa8vJJLi2i79kvqdG0v45g0WgsCQYzLtoNgEUPq%2FG5TgxnuvH39Rv1Jo%2F6l1GeFkDaxGJ3q7rMIvaofcFOusB2IhuY37qi4I3UBGql%2BzH9gsYG4IHeSKT%2FCWYYxu5PhqJQLh%2FR%2Bt8bl9dDfXvHhFtfvO2gSwXXMu8EQKHnzd6ubFFxC1qx%2F5LjLEtU2Pcu9ubT6perprzNNHGPUM1IkofboB2aT60dl%2FULTPMBOpGaHJe5ARGYRQUTVpte5uAqB%2BdxrHJfQnwXMrF7ewQJ4rXpEd58yrW3EnStGIh2xL%2BLK%2BmJt%2FrqJYKFSaelStzknJbg3JHgtT04uMH3S7wSMf8llWyjQnN%2BDCvAplQmNhleYkO61zGlrc%2BhU%2BvBK%2Bo5eaO2BzFI52RbPMgww%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200616T081019Z&X-Amz-SignedHeaders=host&X-Amz-Expires=899&X-Amz-Credential=ASIARA4RDUBFDWDMW3VM%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=5e13067dff7b3a18e048d9625a8f6c1f5b5bb8fd63f90c03be2979492e869183",
              "s3MediumImageUrl": "https://s3.amazonaws.com/skulocity-development/product-images/GZ-1000_medium.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMSJHMEUCIQDkzj1TRHl0yI9N3gX5%2BVadDvPYTD8QgLRyJNuN2%2FqQ3gIgBLrDHS2lAS5JcbL8Gf4PSfDa9MKysrClt8xT2IhG4ngqvQMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNzA2MzQ0MTQxNTQiDK8vg0sITnwokphOACqRA5d2mEmS9j5F%2BgX5vxyuFMdYJxTTG7fnoXmNOIShmXhG7NcsViG5Cdv%2B7ZsVN%2FOTrjaHB7%2B3YgYDKDLmmFuoIXa8sCZD9QY%2BltODB3qqc74A2E5YTPnl3M6Il%2F7F8Qxfnnm34ybNINADdsiwr9JELRO4sus9CIpn3w9Gg5U7zvhNBVGM%2BHjUbpSSFIYNU3op6ZuH%2BymISZNwi5YUXWANnOGQQ%2FKHoko8pW3cNWt%2FT9mkYmTtFcCAHCMpYd8xXEdfqOT3IdomQGayKQN8Vgo3nwxN5w6hV56YJC%2BboMg5GP%2Bial%2Bx3RASWt2yCmqQBDhP6kkQ2Kz4YjOgVA2ki3KrAS2tTb%2BQESe6UF6rojnnNFdWb9faQbLORDFdUAYGYiYrtmIwdA2%2FByzKoqmn%2BwO7d3IDsfH4RGbuleuCc5tTNqonJKTWTrwS%2BnSKv2NONjvS1gNUEVdCu7k9KnrRa8vJJLi2i79kvqdG0v45g0WgsCQYzLtoNgEUPq%2FG5TgxnuvH39Rv1Jo%2F6l1GeFkDaxGJ3q7rMIvaofcFOusB2IhuY37qi4I3UBGql%2BzH9gsYG4IHeSKT%2FCWYYxu5PhqJQLh%2FR%2Bt8bl9dDfXvHhFtfvO2gSwXXMu8EQKHnzd6ubFFxC1qx%2F5LjLEtU2Pcu9ubT6perprzNNHGPUM1IkofboB2aT60dl%2FULTPMBOpGaHJe5ARGYRQUTVpte5uAqB%2BdxrHJfQnwXMrF7ewQJ4rXpEd58yrW3EnStGIh2xL%2BLK%2BmJt%2FrqJYKFSaelStzknJbg3JHgtT04uMH3S7wSMf8llWyjQnN%2BDCvAplQmNhleYkO61zGlrc%2BhU%2BvBK%2Bo5eaO2BzFI52RbPMgww%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200616T081019Z&X-Amz-SignedHeaders=host&X-Amz-Expires=899&X-Amz-Credential=ASIARA4RDUBFDWDMW3VM%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=4abc338759802fd7de7ae5064b19c1a224aa7ad390d44d8171ed6c147e0a6a0a",
              "s3LargeImageUrl": "https://s3.amazonaws.com/skulocity-development/product-images/GZ-1000_large.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMSJHMEUCIQDkzj1TRHl0yI9N3gX5%2BVadDvPYTD8QgLRyJNuN2%2FqQ3gIgBLrDHS2lAS5JcbL8Gf4PSfDa9MKysrClt8xT2IhG4ngqvQMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNzA2MzQ0MTQxNTQiDK8vg0sITnwokphOACqRA5d2mEmS9j5F%2BgX5vxyuFMdYJxTTG7fnoXmNOIShmXhG7NcsViG5Cdv%2B7ZsVN%2FOTrjaHB7%2B3YgYDKDLmmFuoIXa8sCZD9QY%2BltODB3qqc74A2E5YTPnl3M6Il%2F7F8Qxfnnm34ybNINADdsiwr9JELRO4sus9CIpn3w9Gg5U7zvhNBVGM%2BHjUbpSSFIYNU3op6ZuH%2BymISZNwi5YUXWANnOGQQ%2FKHoko8pW3cNWt%2FT9mkYmTtFcCAHCMpYd8xXEdfqOT3IdomQGayKQN8Vgo3nwxN5w6hV56YJC%2BboMg5GP%2Bial%2Bx3RASWt2yCmqQBDhP6kkQ2Kz4YjOgVA2ki3KrAS2tTb%2BQESe6UF6rojnnNFdWb9faQbLORDFdUAYGYiYrtmIwdA2%2FByzKoqmn%2BwO7d3IDsfH4RGbuleuCc5tTNqonJKTWTrwS%2BnSKv2NONjvS1gNUEVdCu7k9KnrRa8vJJLi2i79kvqdG0v45g0WgsCQYzLtoNgEUPq%2FG5TgxnuvH39Rv1Jo%2F6l1GeFkDaxGJ3q7rMIvaofcFOusB2IhuY37qi4I3UBGql%2BzH9gsYG4IHeSKT%2FCWYYxu5PhqJQLh%2FR%2Bt8bl9dDfXvHhFtfvO2gSwXXMu8EQKHnzd6ubFFxC1qx%2F5LjLEtU2Pcu9ubT6perprzNNHGPUM1IkofboB2aT60dl%2FULTPMBOpGaHJe5ARGYRQUTVpte5uAqB%2BdxrHJfQnwXMrF7ewQJ4rXpEd58yrW3EnStGIh2xL%2BLK%2BmJt%2FrqJYKFSaelStzknJbg3JHgtT04uMH3S7wSMf8llWyjQnN%2BDCvAplQmNhleYkO61zGlrc%2BhU%2BvBK%2Bo5eaO2BzFI52RbPMgww%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200616T081019Z&X-Amz-SignedHeaders=host&X-Amz-Expires=899&X-Amz-Credential=ASIARA4RDUBFDWDMW3VM%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=e4f00cfb90a4f96fdc9e09c16d871c05196265b03eab142c7058974bdca1838a",
              "s3DetailImageUrl": "https://s3.amazonaws.com/skulocity-development/https%3A/%2Fracetime.app/img/winner.png?X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMSJHMEUCIQDkzj1TRHl0yI9N3gX5%2BVadDvPYTD8QgLRyJNuN2%2FqQ3gIgBLrDHS2lAS5JcbL8Gf4PSfDa9MKysrClt8xT2IhG4ngqvQMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNzA2MzQ0MTQxNTQiDK8vg0sITnwokphOACqRA5d2mEmS9j5F%2BgX5vxyuFMdYJxTTG7fnoXmNOIShmXhG7NcsViG5Cdv%2B7ZsVN%2FOTrjaHB7%2B3YgYDKDLmmFuoIXa8sCZD9QY%2BltODB3qqc74A2E5YTPnl3M6Il%2F7F8Qxfnnm34ybNINADdsiwr9JELRO4sus9CIpn3w9Gg5U7zvhNBVGM%2BHjUbpSSFIYNU3op6ZuH%2BymISZNwi5YUXWANnOGQQ%2FKHoko8pW3cNWt%2FT9mkYmTtFcCAHCMpYd8xXEdfqOT3IdomQGayKQN8Vgo3nwxN5w6hV56YJC%2BboMg5GP%2Bial%2Bx3RASWt2yCmqQBDhP6kkQ2Kz4YjOgVA2ki3KrAS2tTb%2BQESe6UF6rojnnNFdWb9faQbLORDFdUAYGYiYrtmIwdA2%2FByzKoqmn%2BwO7d3IDsfH4RGbuleuCc5tTNqonJKTWTrwS%2BnSKv2NONjvS1gNUEVdCu7k9KnrRa8vJJLi2i79kvqdG0v45g0WgsCQYzLtoNgEUPq%2FG5TgxnuvH39Rv1Jo%2F6l1GeFkDaxGJ3q7rMIvaofcFOusB2IhuY37qi4I3UBGql%2BzH9gsYG4IHeSKT%2FCWYYxu5PhqJQLh%2FR%2Bt8bl9dDfXvHhFtfvO2gSwXXMu8EQKHnzd6ubFFxC1qx%2F5LjLEtU2Pcu9ubT6perprzNNHGPUM1IkofboB2aT60dl%2FULTPMBOpGaHJe5ARGYRQUTVpte5uAqB%2BdxrHJfQnwXMrF7ewQJ4rXpEd58yrW3EnStGIh2xL%2BLK%2BmJt%2FrqJYKFSaelStzknJbg3JHgtT04uMH3S7wSMf8llWyjQnN%2BDCvAplQmNhleYkO61zGlrc%2BhU%2BvBK%2Bo5eaO2BzFI52RbPMgww%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200616T081019Z&X-Amz-SignedHeaders=host&X-Amz-Expires=899&X-Amz-Credential=ASIARA4RDUBFDWDMW3VM%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=fa0288b0fdc46224278552684bacdbf9036c909c243ac0912a945ba55bd6bc90",
              "s3OriginalImageUrl": "https://s3.amazonaws.com/skulocity-development/product-images/GZ-1000_original.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMSJHMEUCIQDkzj1TRHl0yI9N3gX5%2BVadDvPYTD8QgLRyJNuN2%2FqQ3gIgBLrDHS2lAS5JcbL8Gf4PSfDa9MKysrClt8xT2IhG4ngqvQMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNzA2MzQ0MTQxNTQiDK8vg0sITnwokphOACqRA5d2mEmS9j5F%2BgX5vxyuFMdYJxTTG7fnoXmNOIShmXhG7NcsViG5Cdv%2B7ZsVN%2FOTrjaHB7%2B3YgYDKDLmmFuoIXa8sCZD9QY%2BltODB3qqc74A2E5YTPnl3M6Il%2F7F8Qxfnnm34ybNINADdsiwr9JELRO4sus9CIpn3w9Gg5U7zvhNBVGM%2BHjUbpSSFIYNU3op6ZuH%2BymISZNwi5YUXWANnOGQQ%2FKHoko8pW3cNWt%2FT9mkYmTtFcCAHCMpYd8xXEdfqOT3IdomQGayKQN8Vgo3nwxN5w6hV56YJC%2BboMg5GP%2Bial%2Bx3RASWt2yCmqQBDhP6kkQ2Kz4YjOgVA2ki3KrAS2tTb%2BQESe6UF6rojnnNFdWb9faQbLORDFdUAYGYiYrtmIwdA2%2FByzKoqmn%2BwO7d3IDsfH4RGbuleuCc5tTNqonJKTWTrwS%2BnSKv2NONjvS1gNUEVdCu7k9KnrRa8vJJLi2i79kvqdG0v45g0WgsCQYzLtoNgEUPq%2FG5TgxnuvH39Rv1Jo%2F6l1GeFkDaxGJ3q7rMIvaofcFOusB2IhuY37qi4I3UBGql%2BzH9gsYG4IHeSKT%2FCWYYxu5PhqJQLh%2FR%2Bt8bl9dDfXvHhFtfvO2gSwXXMu8EQKHnzd6ubFFxC1qx%2F5LjLEtU2Pcu9ubT6perprzNNHGPUM1IkofboB2aT60dl%2FULTPMBOpGaHJe5ARGYRQUTVpte5uAqB%2BdxrHJfQnwXMrF7ewQJ4rXpEd58yrW3EnStGIh2xL%2BLK%2BmJt%2FrqJYKFSaelStzknJbg3JHgtT04uMH3S7wSMf8llWyjQnN%2BDCvAplQmNhleYkO61zGlrc%2BhU%2BvBK%2Bo5eaO2BzFI52RbPMgww%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200616T081019Z&X-Amz-SignedHeaders=host&X-Amz-Expires=899&X-Amz-Credential=ASIARA4RDUBFDWDMW3VM%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=a44af2343c05cac405d26b2e09e6789c8bf3f5135d7e4cdbf064b96fa75c49f2"
            },
            "product": {
              "productId": "GZ-1000",
              "productTypeId": "FINISHED_GOOD",
              "primaryProductCategoryId": "101",
              "manufacturerPartyId": null,
              "facilityId": null,
              "introductionDate": null,
              "releaseDate": null,
              "supportDiscontinuationDate": null,
              "salesDiscontinuationDate": null,
              "salesDiscWhenNotAvail": null,
              "internalName": "Tiny Gizmo",
              "brandName": null,
              "comments": null,
              "productName": "Tiny Gizmo",
              "description": "The smallest gizmo in town.",
              "longDescription": "<h2>Long description</h2>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. Diam maecenas ultricies mi eget mauris pharetra et. Aliquam faucibus purus in massa tempor nec feugiat. Dignissim diam quis enim lobortis. Netus et malesuada fames ac turpis egestas. Morbi non arcu risus quis varius. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Viverra nam libero justo laoreet sit amet. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. A diam sollicitudin tempor id eu nisl nunc mi ipsum. Tortor at risus viverra adipiscing at in tellus integer. Adipiscing bibendum est ultricies integer. Amet nulla facilisi morbi tempus iaculis. Duis at tellus at urna.<p>\r\n\r\n<p>Pellentesque habitant morbi tristique senectus et. Placerat in egestas erat imperdiet sed euismod nisi. Ornare suspendisse sed nisi lacus sed viverra. Tellus integer feugiat scelerisque varius morbi enim nunc. Vivamus arcu felis bibendum ut. Pretium lectus quam id leo in vitae turpis massa sed. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Sed ullamcorper morbi tincidunt ornare massa. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Vestibulum lorem sed risus ultricies tristique. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis natoque. Gravida in fermentum et sollicitudin ac orci phasellus.</p>",
              "priceDetailText": null,
              "smallImageUrl": "product-images/GZ-1000_small.jpg",
              "mediumImageUrl": "product-images/GZ-1000_medium.jpg",
              "largeImageUrl": "product-images/GZ-1000_large.jpg",
              "detailImageUrl": "https://racetime.app/img/winner.png",
              "originalImageUrl": "product-images/GZ-1000_original.jpg",
              "detailScreen": null,
              "inventoryMessage": null,
              "requireInventory": null,
              "quantityUomId": null,
              "quantityIncluded": null,
              "piecesIncluded": null,
              "requireAmount": null,
              "fixedAmount": null,
              "amountUomTypeId": null,
              "weightUomId": null,
              "weight": null,
              "productWeight": null,
              "heightUomId": null,
              "productHeight": null,
              "shippingHeight": null,
              "widthUomId": null,
              "productWidth": null,
              "shippingWidth": null,
              "depthUomId": null,
              "productDepth": null,
              "shippingDepth": null,
              "diameterUomId": null,
              "productDiameter": null,
              "productRating": null,
              "ratingTypeEnum": null,
              "returnable": null,
              "taxable": "Y",
              "chargeShipping": "Y",
              "autoCreateKeywords": "Y",
              "includeInPromotions": null,
              "isVirtual": "Y",
              "isVariant": "Y",
              "virtualVariantMethodEnum": null,
              "originGeoId": null,
              "requirementMethodEnumId": "PRODRQM_STOCK",
              "billOfMaterialLevel": 1,
              "reservMaxPersons": null,
              "reserv2ndPPPerc": null,
              "reservNthPPPerc": null,
              "configId": null,
              "createdDate": 989755200000,
              "createdByUserLogin": "admin",
              "lastModifiedDate": 1587627813310,
              "lastModifiedByUserLogin": "admin",
              "inShippingBox": null,
              "defaultShipmentBoxTypeId": null,
              "lastUpdatedStamp": 1587627813310,
              "lastUpdatedTxStamp": 1587627813290,
              "createdStamp": 1575358116740,
              "createdTxStamp": 1575358116671,
              "isActive": null,
              "publishedScopeId": null,
              "shopifyFulfillmentService": null
            }
          }
        },
        {
          "quoteId": "10020",
          "quoteItemSeqId": "00007",
          "productId": "PC001",
          "productFeatureId": null,
          "deliverableTypeId": null,
          "skillTypeId": null,
          "uomId": null,
          "workEffortId": null,
          "custRequestId": null,
          "custRequestItemSeqId": null,
          "quantity": 1.000000,
          "selectedAmount": null,
          "quoteUnitPrice": 50.00,
          "reservStart": null,
          "reservLength": null,
          "reservPersons": null,
          "configId": null,
          "estimatedDeliveryDate": null,
          "comments": null,
          "isPromo": null,
          "lastUpdatedStamp": 1584952766175,
          "lastUpdatedTxStamp": 1584952766161,
          "createdStamp": 1584952766169,
          "createdTxStamp": 1584952766161,
          "description": "Configurable PC",
          "quoteApproval": {
            "productId": "PC001",
            "quoteItemSeqId": "00007",
            "quoteId": "10020",
            "isApproved": "Y",
            "comments": "432",
            "lastUpdatedStamp": 1585652397966,
            "lastUpdatedTxStamp": 1585652397966,
            "createdStamp": 1585652397966,
            "createdTxStamp": 1585652397966
          },
          "totalQuoteItemAdjustmentAmount": 0.0,
          "totalQuoteItemAmount": 50.0,
          "productContent": {
            "imageServerPath": "/home/ubuntu/skulocity-opentaps/skulocity-opentaps/framework/images/webapp/images",
            "imageNameLarge": "/images/products/large/PC001",
            "tryEntity": true,
            "imageNameMedium": "/images/products/medium/PC001",
            "imageNameOriginal": "/images/products/original/PC001",
            "productContent": [
  
            ],
            "imageFilenameFormat": "${location}/${type}/${id}",
            "imageUrlPrefix": "/images",
            "imageNameSmall": "/images/products/small/PC001",
            "imageNameDetail": "/images/products/detail/PC001",
            "responseMessage": "success",
            "imageMap": {
              "s3SmallImageUrl": "https://s3.amazonaws.com/skulocity-development/%2Fimages/products/small/gis_computer_glen_rolla.png?X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMSJHMEUCIQDkzj1TRHl0yI9N3gX5%2BVadDvPYTD8QgLRyJNuN2%2FqQ3gIgBLrDHS2lAS5JcbL8Gf4PSfDa9MKysrClt8xT2IhG4ngqvQMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNzA2MzQ0MTQxNTQiDK8vg0sITnwokphOACqRA5d2mEmS9j5F%2BgX5vxyuFMdYJxTTG7fnoXmNOIShmXhG7NcsViG5Cdv%2B7ZsVN%2FOTrjaHB7%2B3YgYDKDLmmFuoIXa8sCZD9QY%2BltODB3qqc74A2E5YTPnl3M6Il%2F7F8Qxfnnm34ybNINADdsiwr9JELRO4sus9CIpn3w9Gg5U7zvhNBVGM%2BHjUbpSSFIYNU3op6ZuH%2BymISZNwi5YUXWANnOGQQ%2FKHoko8pW3cNWt%2FT9mkYmTtFcCAHCMpYd8xXEdfqOT3IdomQGayKQN8Vgo3nwxN5w6hV56YJC%2BboMg5GP%2Bial%2Bx3RASWt2yCmqQBDhP6kkQ2Kz4YjOgVA2ki3KrAS2tTb%2BQESe6UF6rojnnNFdWb9faQbLORDFdUAYGYiYrtmIwdA2%2FByzKoqmn%2BwO7d3IDsfH4RGbuleuCc5tTNqonJKTWTrwS%2BnSKv2NONjvS1gNUEVdCu7k9KnrRa8vJJLi2i79kvqdG0v45g0WgsCQYzLtoNgEUPq%2FG5TgxnuvH39Rv1Jo%2F6l1GeFkDaxGJ3q7rMIvaofcFOusB2IhuY37qi4I3UBGql%2BzH9gsYG4IHeSKT%2FCWYYxu5PhqJQLh%2FR%2Bt8bl9dDfXvHhFtfvO2gSwXXMu8EQKHnzd6ubFFxC1qx%2F5LjLEtU2Pcu9ubT6perprzNNHGPUM1IkofboB2aT60dl%2FULTPMBOpGaHJe5ARGYRQUTVpte5uAqB%2BdxrHJfQnwXMrF7ewQJ4rXpEd58yrW3EnStGIh2xL%2BLK%2BmJt%2FrqJYKFSaelStzknJbg3JHgtT04uMH3S7wSMf8llWyjQnN%2BDCvAplQmNhleYkO61zGlrc%2BhU%2BvBK%2Bo5eaO2BzFI52RbPMgww%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200616T081020Z&X-Amz-SignedHeaders=host&X-Amz-Expires=899&X-Amz-Credential=ASIARA4RDUBFDWDMW3VM%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=5cd67679f82751b700f31bb8cc773c9e60c56826ca39a355aefe72440ad16f94",
              "s3LargeImageUrl": "https://s3.amazonaws.com/skulocity-development/%2Fimages/products/large/gis_computer_glen_rolla.png?X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMSJHMEUCIQDkzj1TRHl0yI9N3gX5%2BVadDvPYTD8QgLRyJNuN2%2FqQ3gIgBLrDHS2lAS5JcbL8Gf4PSfDa9MKysrClt8xT2IhG4ngqvQMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNzA2MzQ0MTQxNTQiDK8vg0sITnwokphOACqRA5d2mEmS9j5F%2BgX5vxyuFMdYJxTTG7fnoXmNOIShmXhG7NcsViG5Cdv%2B7ZsVN%2FOTrjaHB7%2B3YgYDKDLmmFuoIXa8sCZD9QY%2BltODB3qqc74A2E5YTPnl3M6Il%2F7F8Qxfnnm34ybNINADdsiwr9JELRO4sus9CIpn3w9Gg5U7zvhNBVGM%2BHjUbpSSFIYNU3op6ZuH%2BymISZNwi5YUXWANnOGQQ%2FKHoko8pW3cNWt%2FT9mkYmTtFcCAHCMpYd8xXEdfqOT3IdomQGayKQN8Vgo3nwxN5w6hV56YJC%2BboMg5GP%2Bial%2Bx3RASWt2yCmqQBDhP6kkQ2Kz4YjOgVA2ki3KrAS2tTb%2BQESe6UF6rojnnNFdWb9faQbLORDFdUAYGYiYrtmIwdA2%2FByzKoqmn%2BwO7d3IDsfH4RGbuleuCc5tTNqonJKTWTrwS%2BnSKv2NONjvS1gNUEVdCu7k9KnrRa8vJJLi2i79kvqdG0v45g0WgsCQYzLtoNgEUPq%2FG5TgxnuvH39Rv1Jo%2F6l1GeFkDaxGJ3q7rMIvaofcFOusB2IhuY37qi4I3UBGql%2BzH9gsYG4IHeSKT%2FCWYYxu5PhqJQLh%2FR%2Bt8bl9dDfXvHhFtfvO2gSwXXMu8EQKHnzd6ubFFxC1qx%2F5LjLEtU2Pcu9ubT6perprzNNHGPUM1IkofboB2aT60dl%2FULTPMBOpGaHJe5ARGYRQUTVpte5uAqB%2BdxrHJfQnwXMrF7ewQJ4rXpEd58yrW3EnStGIh2xL%2BLK%2BmJt%2FrqJYKFSaelStzknJbg3JHgtT04uMH3S7wSMf8llWyjQnN%2BDCvAplQmNhleYkO61zGlrc%2BhU%2BvBK%2Bo5eaO2BzFI52RbPMgww%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200616T081020Z&X-Amz-SignedHeaders=host&X-Amz-Expires=899&X-Amz-Credential=ASIARA4RDUBFDWDMW3VM%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=fc5e7fde0d49094066a866e46ac3fe8103f29a65c13661c532b734b5da044afa"
            },
            "product": {
              "productId": "PC001",
              "productTypeId": "AGGREGATED",
              "primaryProductCategoryId": null,
              "manufacturerPartyId": null,
              "facilityId": null,
              "introductionDate": null,
              "releaseDate": null,
              "supportDiscontinuationDate": null,
              "salesDiscontinuationDate": null,
              "salesDiscWhenNotAvail": null,
              "internalName": "Configurable PC",
              "brandName": null,
              "comments": null,
              "productName": "Configurable PC",
              "description": "Configurable PC",
              "longDescription": null,
              "priceDetailText": null,
              "smallImageUrl": "/images/products/small/gis_computer_glen_rolla.png",
              "mediumImageUrl": null,
              "largeImageUrl": "/images/products/large/gis_computer_glen_rolla.png",
              "detailImageUrl": null,
              "originalImageUrl": null,
              "detailScreen": null,
              "inventoryMessage": null,
              "requireInventory": null,
              "quantityUomId": null,
              "quantityIncluded": null,
              "piecesIncluded": null,
              "requireAmount": null,
              "fixedAmount": null,
              "amountUomTypeId": null,
              "weightUomId": null,
              "weight": null,
              "productWeight": null,
              "heightUomId": null,
              "productHeight": null,
              "shippingHeight": null,
              "widthUomId": null,
              "productWidth": null,
              "shippingWidth": null,
              "depthUomId": null,
              "productDepth": null,
              "shippingDepth": null,
              "diameterUomId": null,
              "productDiameter": null,
              "productRating": null,
              "ratingTypeEnum": null,
              "returnable": null,
              "taxable": null,
              "chargeShipping": null,
              "autoCreateKeywords": null,
              "includeInPromotions": null,
              "isVirtual": "N",
              "isVariant": "N",
              "virtualVariantMethodEnum": null,
              "originGeoId": null,
              "requirementMethodEnumId": null,
              "billOfMaterialLevel": 0,
              "reservMaxPersons": null,
              "reserv2ndPPPerc": null,
              "reservNthPPPerc": null,
              "configId": null,
              "createdDate": 1093006153418,
              "createdByUserLogin": "admin",
              "lastModifiedDate": null,
              "lastModifiedByUserLogin": null,
              "inShippingBox": null,
              "defaultShipmentBoxTypeId": null,
              "lastUpdatedStamp": 1575358128670,
              "lastUpdatedTxStamp": 1575358128639,
              "createdStamp": 1575358127612,
              "createdTxStamp": 1575358127204,
              "isActive": null,
              "publishedScopeId": null,
              "shopifyFulfillmentService": null
            }
          }
        },
        {
          "quoteId": "10020",
          "quoteItemSeqId": "00008",
          "productId": "PC001",
          "productFeatureId": null,
          "deliverableTypeId": null,
          "skillTypeId": null,
          "uomId": null,
          "workEffortId": null,
          "custRequestId": null,
          "custRequestItemSeqId": null,
          "quantity": 1.000000,
          "selectedAmount": null,
          "quoteUnitPrice": 50.00,
          "reservStart": null,
          "reservLength": null,
          "reservPersons": null,
          "configId": null,
          "estimatedDeliveryDate": null,
          "comments": null,
          "isPromo": null,
          "lastUpdatedStamp": 1584952894359,
          "lastUpdatedTxStamp": 1584952894335,
          "createdStamp": 1584952894348,
          "createdTxStamp": 1584952894335,
          "description": "Configurable PC",
          "quoteApproval": {
            "productId": "PC001",
            "quoteItemSeqId": "00008",
            "quoteId": "10020",
            "isApproved": "N",
            "comments": "",
            "lastUpdatedStamp": 1585652397984,
            "lastUpdatedTxStamp": 1585652397984,
            "createdStamp": 1585652397984,
            "createdTxStamp": 1585652397984
          },
          "totalQuoteItemAdjustmentAmount": 0.0,
          "totalQuoteItemAmount": 50.0,
          "productContent": {
            "imageServerPath": "/home/ubuntu/skulocity-opentaps/skulocity-opentaps/framework/images/webapp/images",
            "imageNameLarge": "/images/products/large/PC001",
            "tryEntity": true,
            "imageNameMedium": "/images/products/medium/PC001",
            "imageNameOriginal": "/images/products/original/PC001",
            "productContent": [
  
            ],
            "imageFilenameFormat": "${location}/${type}/${id}",
            "imageUrlPrefix": "/images",
            "imageNameSmall": "/images/products/small/PC001",
            "imageNameDetail": "/images/products/detail/PC001",
            "responseMessage": "success",
            "imageMap": {
              "s3SmallImageUrl": "https://s3.amazonaws.com/skulocity-development/%2Fimages/products/small/gis_computer_glen_rolla.png?X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMSJHMEUCIQDkzj1TRHl0yI9N3gX5%2BVadDvPYTD8QgLRyJNuN2%2FqQ3gIgBLrDHS2lAS5JcbL8Gf4PSfDa9MKysrClt8xT2IhG4ngqvQMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNzA2MzQ0MTQxNTQiDK8vg0sITnwokphOACqRA5d2mEmS9j5F%2BgX5vxyuFMdYJxTTG7fnoXmNOIShmXhG7NcsViG5Cdv%2B7ZsVN%2FOTrjaHB7%2B3YgYDKDLmmFuoIXa8sCZD9QY%2BltODB3qqc74A2E5YTPnl3M6Il%2F7F8Qxfnnm34ybNINADdsiwr9JELRO4sus9CIpn3w9Gg5U7zvhNBVGM%2BHjUbpSSFIYNU3op6ZuH%2BymISZNwi5YUXWANnOGQQ%2FKHoko8pW3cNWt%2FT9mkYmTtFcCAHCMpYd8xXEdfqOT3IdomQGayKQN8Vgo3nwxN5w6hV56YJC%2BboMg5GP%2Bial%2Bx3RASWt2yCmqQBDhP6kkQ2Kz4YjOgVA2ki3KrAS2tTb%2BQESe6UF6rojnnNFdWb9faQbLORDFdUAYGYiYrtmIwdA2%2FByzKoqmn%2BwO7d3IDsfH4RGbuleuCc5tTNqonJKTWTrwS%2BnSKv2NONjvS1gNUEVdCu7k9KnrRa8vJJLi2i79kvqdG0v45g0WgsCQYzLtoNgEUPq%2FG5TgxnuvH39Rv1Jo%2F6l1GeFkDaxGJ3q7rMIvaofcFOusB2IhuY37qi4I3UBGql%2BzH9gsYG4IHeSKT%2FCWYYxu5PhqJQLh%2FR%2Bt8bl9dDfXvHhFtfvO2gSwXXMu8EQKHnzd6ubFFxC1qx%2F5LjLEtU2Pcu9ubT6perprzNNHGPUM1IkofboB2aT60dl%2FULTPMBOpGaHJe5ARGYRQUTVpte5uAqB%2BdxrHJfQnwXMrF7ewQJ4rXpEd58yrW3EnStGIh2xL%2BLK%2BmJt%2FrqJYKFSaelStzknJbg3JHgtT04uMH3S7wSMf8llWyjQnN%2BDCvAplQmNhleYkO61zGlrc%2BhU%2BvBK%2Bo5eaO2BzFI52RbPMgww%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200616T081020Z&X-Amz-SignedHeaders=host&X-Amz-Expires=899&X-Amz-Credential=ASIARA4RDUBFDWDMW3VM%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=5cd67679f82751b700f31bb8cc773c9e60c56826ca39a355aefe72440ad16f94",
              "s3LargeImageUrl": "https://s3.amazonaws.com/skulocity-development/%2Fimages/products/large/gis_computer_glen_rolla.png?X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMSJHMEUCIQDkzj1TRHl0yI9N3gX5%2BVadDvPYTD8QgLRyJNuN2%2FqQ3gIgBLrDHS2lAS5JcbL8Gf4PSfDa9MKysrClt8xT2IhG4ngqvQMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNzA2MzQ0MTQxNTQiDK8vg0sITnwokphOACqRA5d2mEmS9j5F%2BgX5vxyuFMdYJxTTG7fnoXmNOIShmXhG7NcsViG5Cdv%2B7ZsVN%2FOTrjaHB7%2B3YgYDKDLmmFuoIXa8sCZD9QY%2BltODB3qqc74A2E5YTPnl3M6Il%2F7F8Qxfnnm34ybNINADdsiwr9JELRO4sus9CIpn3w9Gg5U7zvhNBVGM%2BHjUbpSSFIYNU3op6ZuH%2BymISZNwi5YUXWANnOGQQ%2FKHoko8pW3cNWt%2FT9mkYmTtFcCAHCMpYd8xXEdfqOT3IdomQGayKQN8Vgo3nwxN5w6hV56YJC%2BboMg5GP%2Bial%2Bx3RASWt2yCmqQBDhP6kkQ2Kz4YjOgVA2ki3KrAS2tTb%2BQESe6UF6rojnnNFdWb9faQbLORDFdUAYGYiYrtmIwdA2%2FByzKoqmn%2BwO7d3IDsfH4RGbuleuCc5tTNqonJKTWTrwS%2BnSKv2NONjvS1gNUEVdCu7k9KnrRa8vJJLi2i79kvqdG0v45g0WgsCQYzLtoNgEUPq%2FG5TgxnuvH39Rv1Jo%2F6l1GeFkDaxGJ3q7rMIvaofcFOusB2IhuY37qi4I3UBGql%2BzH9gsYG4IHeSKT%2FCWYYxu5PhqJQLh%2FR%2Bt8bl9dDfXvHhFtfvO2gSwXXMu8EQKHnzd6ubFFxC1qx%2F5LjLEtU2Pcu9ubT6perprzNNHGPUM1IkofboB2aT60dl%2FULTPMBOpGaHJe5ARGYRQUTVpte5uAqB%2BdxrHJfQnwXMrF7ewQJ4rXpEd58yrW3EnStGIh2xL%2BLK%2BmJt%2FrqJYKFSaelStzknJbg3JHgtT04uMH3S7wSMf8llWyjQnN%2BDCvAplQmNhleYkO61zGlrc%2BhU%2BvBK%2Bo5eaO2BzFI52RbPMgww%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200616T081020Z&X-Amz-SignedHeaders=host&X-Amz-Expires=899&X-Amz-Credential=ASIARA4RDUBFDWDMW3VM%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=fc5e7fde0d49094066a866e46ac3fe8103f29a65c13661c532b734b5da044afa"
            },
            "product": {
              "productId": "PC001",
              "productTypeId": "AGGREGATED",
              "primaryProductCategoryId": null,
              "manufacturerPartyId": null,
              "facilityId": null,
              "introductionDate": null,
              "releaseDate": null,
              "supportDiscontinuationDate": null,
              "salesDiscontinuationDate": null,
              "salesDiscWhenNotAvail": null,
              "internalName": "Configurable PC",
              "brandName": null,
              "comments": null,
              "productName": "Configurable PC",
              "description": "Configurable PC",
              "longDescription": null,
              "priceDetailText": null,
              "smallImageUrl": "/images/products/small/gis_computer_glen_rolla.png",
              "mediumImageUrl": null,
              "largeImageUrl": "/images/products/large/gis_computer_glen_rolla.png",
              "detailImageUrl": null,
              "originalImageUrl": null,
              "detailScreen": null,
              "inventoryMessage": null,
              "requireInventory": null,
              "quantityUomId": null,
              "quantityIncluded": null,
              "piecesIncluded": null,
              "requireAmount": null,
              "fixedAmount": null,
              "amountUomTypeId": null,
              "weightUomId": null,
              "weight": null,
              "productWeight": null,
              "heightUomId": null,
              "productHeight": null,
              "shippingHeight": null,
              "widthUomId": null,
              "productWidth": null,
              "shippingWidth": null,
              "depthUomId": null,
              "productDepth": null,
              "shippingDepth": null,
              "diameterUomId": null,
              "productDiameter": null,
              "productRating": null,
              "ratingTypeEnum": null,
              "returnable": null,
              "taxable": null,
              "chargeShipping": null,
              "autoCreateKeywords": null,
              "includeInPromotions": null,
              "isVirtual": "N",
              "isVariant": "N",
              "virtualVariantMethodEnum": null,
              "originGeoId": null,
              "requirementMethodEnumId": null,
              "billOfMaterialLevel": 0,
              "reservMaxPersons": null,
              "reserv2ndPPPerc": null,
              "reservNthPPPerc": null,
              "configId": null,
              "createdDate": 1093006153418,
              "createdByUserLogin": "admin",
              "lastModifiedDate": null,
              "lastModifiedByUserLogin": null,
              "inShippingBox": null,
              "defaultShipmentBoxTypeId": null,
              "lastUpdatedStamp": 1575358128670,
              "lastUpdatedTxStamp": 1575358128639,
              "createdStamp": 1575358127612,
              "createdTxStamp": 1575358127204,
              "isActive": null,
              "publishedScopeId": null,
              "shopifyFulfillmentService": null
            }
          }
        },
        {
          "quoteId": "10020",
          "quoteItemSeqId": "00009",
          "productId": "GZ-1006-3",
          "productFeatureId": null,
          "deliverableTypeId": null,
          "skillTypeId": null,
          "uomId": null,
          "workEffortId": null,
          "custRequestId": null,
          "custRequestItemSeqId": null,
          "quantity": 1.000000,
          "selectedAmount": null,
          "quoteUnitPrice": 1.99,
          "reservStart": null,
          "reservLength": null,
          "reservPersons": null,
          "configId": null,
          "estimatedDeliveryDate": null,
          "comments": null,
          "isPromo": null,
          "lastUpdatedStamp": 1586248069027,
          "lastUpdatedTxStamp": 1586248068993,
          "createdStamp": 1586248069018,
          "createdTxStamp": 1586248068993,
          "description": "Open Gizmo (BSD)",
          "totalQuoteItemAdjustmentAmount": 0.0,
          "totalQuoteItemAmount": 1.99,
          "productContent": {
            "imageServerPath": "/home/ubuntu/skulocity-opentaps/skulocity-opentaps/framework/images/webapp/images",
            "imageNameLarge": "/images/products/large/GZ-1006-3",
            "tryEntity": true,
            "imageNameMedium": "/images/products/medium/GZ-1006-3",
            "imageNameOriginal": "/images/products/original/GZ-1006-3",
            "productContent": [
              {
                "productId": "GZ-1006-3",
                "contentId": "10160",
                "productContentTypeId": "SPECIFICATION",
                "fromDate": 1586131200000,
                "thruDate": 1586995200000,
                "purchaseFromDate": 1586131200000,
                "purchaseThruDate": 1587513600000,
                "useCountLimit": null,
                "useTime": null,
                "useTimeUomId": null,
                "useRoleTypeId": null,
                "lastUpdatedStamp": 1586945967876,
                "lastUpdatedTxStamp": 1586945967698,
                "createdStamp": 1586945289976,
                "createdTxStamp": 1586945289614
              }
            ],
            "imageFilenameFormat": "${location}/${type}/${id}",
            "imageUrlPrefix": "/images",
            "imageNameSmall": "/images/products/small/GZ-1006-3",
            "imageNameDetail": "/images/products/detail/GZ-1006-3",
            "responseMessage": "success",
            "imageMap": {
              "s3SmallImageUrl": "https://s3.amazonaws.com/skulocity-development/product-images/GZ-1006-3_small.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMSJHMEUCIQDkzj1TRHl0yI9N3gX5%2BVadDvPYTD8QgLRyJNuN2%2FqQ3gIgBLrDHS2lAS5JcbL8Gf4PSfDa9MKysrClt8xT2IhG4ngqvQMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNzA2MzQ0MTQxNTQiDK8vg0sITnwokphOACqRA5d2mEmS9j5F%2BgX5vxyuFMdYJxTTG7fnoXmNOIShmXhG7NcsViG5Cdv%2B7ZsVN%2FOTrjaHB7%2B3YgYDKDLmmFuoIXa8sCZD9QY%2BltODB3qqc74A2E5YTPnl3M6Il%2F7F8Qxfnnm34ybNINADdsiwr9JELRO4sus9CIpn3w9Gg5U7zvhNBVGM%2BHjUbpSSFIYNU3op6ZuH%2BymISZNwi5YUXWANnOGQQ%2FKHoko8pW3cNWt%2FT9mkYmTtFcCAHCMpYd8xXEdfqOT3IdomQGayKQN8Vgo3nwxN5w6hV56YJC%2BboMg5GP%2Bial%2Bx3RASWt2yCmqQBDhP6kkQ2Kz4YjOgVA2ki3KrAS2tTb%2BQESe6UF6rojnnNFdWb9faQbLORDFdUAYGYiYrtmIwdA2%2FByzKoqmn%2BwO7d3IDsfH4RGbuleuCc5tTNqonJKTWTrwS%2BnSKv2NONjvS1gNUEVdCu7k9KnrRa8vJJLi2i79kvqdG0v45g0WgsCQYzLtoNgEUPq%2FG5TgxnuvH39Rv1Jo%2F6l1GeFkDaxGJ3q7rMIvaofcFOusB2IhuY37qi4I3UBGql%2BzH9gsYG4IHeSKT%2FCWYYxu5PhqJQLh%2FR%2Bt8bl9dDfXvHhFtfvO2gSwXXMu8EQKHnzd6ubFFxC1qx%2F5LjLEtU2Pcu9ubT6perprzNNHGPUM1IkofboB2aT60dl%2FULTPMBOpGaHJe5ARGYRQUTVpte5uAqB%2BdxrHJfQnwXMrF7ewQJ4rXpEd58yrW3EnStGIh2xL%2BLK%2BmJt%2FrqJYKFSaelStzknJbg3JHgtT04uMH3S7wSMf8llWyjQnN%2BDCvAplQmNhleYkO61zGlrc%2BhU%2BvBK%2Bo5eaO2BzFI52RbPMgww%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200616T081020Z&X-Amz-SignedHeaders=host&X-Amz-Expires=899&X-Amz-Credential=ASIARA4RDUBFDWDMW3VM%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=af64da4bcb58fb8cc76a9cb8e1849e1564a41194b3c7ed7ced445d204c3f2320",
              "s3MediumImageUrl": "https://s3.amazonaws.com/skulocity-development/product-images/GZ-1006-3_medium.jpeg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjED8aCXVzLWVhc3QtMSJHMEUCIQDkzj1TRHl0yI9N3gX5%2BVadDvPYTD8QgLRyJNuN2%2FqQ3gIgBLrDHS2lAS5JcbL8Gf4PSfDa9MKysrClt8xT2IhG4ngqvQMIuP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARACGgwwNzA2MzQ0MTQxNTQiDK8vg0sITnwokphOACqRA5d2mEmS9j5F%2BgX5vxyuFMdYJxTTG7fnoXmNOIShmXhG7NcsViG5Cdv%2B7ZsVN%2FOTrjaHB7%2B3YgYDKDLmmFuoIXa8sCZD9QY%2BltODB3qqc74A2E5YTPnl3M6Il%2F7F8Qxfnnm34ybNINADdsiwr9JELRO4sus9CIpn3w9Gg5U7zvhNBVGM%2BHjUbpSSFIYNU3op6ZuH%2BymISZNwi5YUXWANnOGQQ%2FKHoko8pW3cNWt%2FT9mkYmTtFcCAHCMpYd8xXEdfqOT3IdomQGayKQN8Vgo3nwxN5w6hV56YJC%2BboMg5GP%2Bial%2Bx3RASWt2yCmqQBDhP6kkQ2Kz4YjOgVA2ki3KrAS2tTb%2BQESe6UF6rojnnNFdWb9faQbLORDFdUAYGYiYrtmIwdA2%2FByzKoqmn%2BwO7d3IDsfH4RGbuleuCc5tTNqonJKTWTrwS%2BnSKv2NONjvS1gNUEVdCu7k9KnrRa8vJJLi2i79kvqdG0v45g0WgsCQYzLtoNgEUPq%2FG5TgxnuvH39Rv1Jo%2F6l1GeFkDaxGJ3q7rMIvaofcFOusB2IhuY37qi4I3UBGql%2BzH9gsYG4IHeSKT%2FCWYYxu5PhqJQLh%2FR%2Bt8bl9dDfXvHhFtfvO2gSwXXMu8EQKHnzd6ubFFxC1qx%2F5LjLEtU2Pcu9ubT6perprzNNHGPUM1IkofboB2aT60dl%2FULTPMBOpGaHJe5ARGYRQUTVpte5uAqB%2BdxrHJfQnwXMrF7ewQJ4rXpEd58yrW3EnStGIh2xL%2BLK%2BmJt%2FrqJYKFSaelStzknJbg3JHgtT04uMH3S7wSMf8llWyjQnN%2BDCvAplQmNhleYkO61zGlrc%2BhU%2BvBK%2Bo5eaO2BzFI52RbPMgww%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200616T081020Z&X-Amz-SignedHeaders=host&X-Amz-Expires=899&X-Amz-Credential=ASIARA4RDUBFDWDMW3VM%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=663e6d95b97e6276e8ed0476a8ee2414205db1d8d4f41c4c4c0d0f199666d9be"
            },
            "product": {
              "productId": "GZ-1006-3",
              "productTypeId": "FINISHED_GOOD",
              "primaryProductCategoryId": "102",
              "manufacturerPartyId": null,
              "facilityId": null,
              "introductionDate": null,
              "releaseDate": null,
              "supportDiscontinuationDate": null,
              "salesDiscontinuationDate": null,
              "salesDiscWhenNotAvail": null,
              "internalName": "Open Gizmo (BSD)",
              "brandName": null,
              "comments": null,
              "productName": "Open Gizmo (BSD)",
              "description": "Gizmo based on open standards",
              "longDescription": "Highest quality gizmo around.",
              "priceDetailText": null,
              "smallImageUrl": "product-images/GZ-1006-3_small.jpg",
              "mediumImageUrl": "product-images/GZ-1006-3_medium.jpeg",
              "largeImageUrl": null,
              "detailImageUrl": null,
              "originalImageUrl": null,
              "detailScreen": null,
              "inventoryMessage": null,
              "requireInventory": null,
              "quantityUomId": null,
              "quantityIncluded": null,
              "piecesIncluded": null,
              "requireAmount": null,
              "fixedAmount": null,
              "amountUomTypeId": null,
              "weightUomId": null,
              "weight": null,
              "productWeight": null,
              "heightUomId": null,
              "productHeight": null,
              "shippingHeight": null,
              "widthUomId": null,
              "productWidth": null,
              "shippingWidth": null,
              "depthUomId": null,
              "productDepth": null,
              "shippingDepth": null,
              "diameterUomId": null,
              "productDiameter": null,
              "productRating": null,
              "ratingTypeEnum": null,
              "returnable": null,
              "taxable": "Y",
              "chargeShipping": "Y",
              "autoCreateKeywords": "Y",
              "includeInPromotions": null,
              "isVirtual": "N",
              "isVariant": "Y",
              "virtualVariantMethodEnum": null,
              "originGeoId": null,
              "requirementMethodEnumId": null,
              "billOfMaterialLevel": null,
              "reservMaxPersons": null,
              "reserv2ndPPPerc": null,
              "reservNthPPPerc": null,
              "configId": null,
              "createdDate": 989755200000,
              "createdByUserLogin": "admin",
              "lastModifiedDate": 1586945967920,
              "lastModifiedByUserLogin": "system",
              "inShippingBox": null,
              "defaultShipmentBoxTypeId": null,
              "lastUpdatedStamp": 1586945967921,
              "lastUpdatedTxStamp": 1586945967698,
              "createdStamp": 1575358121689,
              "createdTxStamp": 1575358121352,
              "isActive": null,
              "publishedScopeId": null,
              "shopifyFulfillmentService": null
            }
          }
        }
      ]
    }

    this.quoteDetails();
  }

  quoteDetails(): void {
    this.urlSubscriber = this.route.paramMap.subscribe((data: any) => {
      const quoteId = data.params.quoteId;

      for(let key in this.resp)
      {
        console.log(this.resp[key]);
      }

      this.dashboardService.getQuoteDetails(quoteId).subscribe((res) => {
        console.log(res);
      })
    });
  }

}
